theme: jekyll-theme-architect
title: Bienvenido a la página de inicio de Miguel García López!
description: Feel free to bookmark this to keep an eye o0n my project updates
#Sesion 03#
DNS de la máquina con GitLab:  http://fls789-hmis18-vm1.eastus.cloudapp.azure.com/
DNS de la máquina con Jenkins: http://mgl958-hmis18-vm2.eastus.cloudapp.azure.com/
Nombre del repositorio GitLab con ejercicios : http://fls789-hmis18-vm1.eastus.cloudapp.azure.com/mgl958/hmis18-sesion03-git.git
